"""reconcile models with database

Revision ID: fbc5d1c4be51
Revises: b596c83109eb
Create Date: 2026-04-13 13:15:49.592407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbc5d1c4be51'
down_revision: Union[str, Sequence[str], None] = 'b596c83109eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_pending_verifications_email'), 'pending_verifications', type_='unique')
    op.drop_column('staff_users', 'account_setup_complete')
    op.drop_column('staff_users', 'totp_secret')
    op.drop_column('staff_users', 'totp_enabled')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_users', sa.Column('totp_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('staff_users', sa.Column('totp_secret', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('staff_users', sa.Column('account_setup_complete', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('uq_pending_verifications_email'), 'pending_verifications', ['email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
